foreground         #c4c3c3
background         #131210
background_opacity 1.0
cursor             #c4c3c3

active_tab_foreground     #131210
active_tab_background     #c4c3c3
inactive_tab_foreground   #c4c3c3
inactive_tab_background   #131210

active_border_color   #c4c3c3
inactive_border_color #131210
bell_border_color     #aa9e8e

color0       #131210
color8       #6e6459
color1       #aa9e8e
color9       #aa9e8e
color2       #a9a296
color10      #a9a296
color3       #a9a79b
color11      #a9a79b
color4       #a8a9a4
color12      #a8a9a4
color5       #9da8a5
color13      #9da8a5
color6       #91a4a9
color14      #91a4a9
color7       #c4c3c3
color15      #c4c3c3
