# Pywal Colors for Hyprland
$background = rgb(131210)
$foreground = rgb(c4c3c3)
$color0 = rgb(131210)
$color1 = rgb(aa9e8e)
$color2 = rgb(a9a296)
$color3 = rgb(a9a79b)
$color4 = rgb(a8a9a4)
$color5 = rgb(9da8a5)
$color6 = rgb(91a4a9)
$color7 = rgb(c4c3c3)
$color8 = rgb(6e6459)
$color9 = rgb(aa9e8e)
$color10 = rgb(a9a296)
$color11 = rgb(a9a79b)
$color12 = rgb(a8a9a4)
$color13 = rgb(9da8a5)
$color14 = rgb(91a4a9)
$color15 = rgb(c4c3c3)

